# Generated by Django 5.2.4 on 2025-07-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communitymember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityMember',
        ),
    ]
