# Generated by Django 5.2.4 on 2025-07-04 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_remove_community_members_communitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitymember',
            name='user',
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommunityLog',
        ),
        migrations.DeleteModel(
            name='CommunityMember',
        ),
    ]
