# Generated by Django 5.2.4 on 2025-07-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_communitymember_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityQuestion',
        ),
    ]
