# Generated by Django 5.2.4 on 2025-07-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('answer', 'New Answer'), ('question_vote', 'Question Vote'), ('answer_vote', 'Answer Vote'), ('answer_accepted', 'Answer Accepted'), ('mention', 'Mention'), ('follow', 'New Follower'), ('bookmark', 'Question Bookmarked'), ('community_invite', 'Community Invitation'), ('community_question', 'Community Question'), ('community_join_request', 'Community Join Request'), ('community_request_approved', 'Community Request Approved'), ('community_request_declined', 'Community Request Declined'), ('community_post', 'Community Post'), ('community_admin_assigned', 'Community Admin Assigned'), ('system', 'System Notification')], max_length=30),
        ),
    ]
